### ISSUE TITLE
Problem with building hackage encoding-0.8.3

### ISSUE THREAD

**Issue by rpeszek** [dmwit/encoding#8]
I am trying to use encoding-0.8.3  
(actually, I am writing a bridge between my https://github.com/rpeszek/typed-encoding and `encoding`)

It builds FINE with stack if, in `stack.yaml`, I specify 
```
- git: git@github.com:dmwit/encoding
  commit: 0.8.3
```
but not if I put hackage version
```
- encoding-0.8.3
```
I tried `lts-14.27` and then the same lts as you use: `lts-13.0`

The same is true using `cabal v2-build` (using ghc 8.2.2) when I specify 
encoding-0.8.3 in cabal file.
I tired this on a test project where encoding-0.8.3 was the only dependency.

I suspect something went wrong with pre-processors in `Setup.hs` when the
distribution was created. 
The error message:
```
[9 of 9] Compiling StackSetupShim   ( /home/rpeszek/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack10595/encoding-0.8.3/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/setup/StackSetupShim.o )
    Linking /tmp/stack10595/encoding-0.8.3/.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/setup/setup ...
    Configuring encoding-0.8.3...
    Preprocessing library for encoding-0.8.3..
    setup: can't find source for Data/Encoding/ISO88591 in .,
    .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/autogen,
    .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/global-autogen
```

**Comment by swamp-agr** [comment]
Hi @rpeszek,

I reproduced issue locally and was able to find root cause of it:

- `Data.Encoding.ISO88591` was placed in `Autogen-Modules` stanza: https://github.com/dmwit/encoding/blob/master/encoding.cabal#L128 
- Meantime, it is present as a regular module, it should not be autogenerated: https://github.com/dmwit/encoding/blob/master/Data/Encoding/ISO88591.hs

Please expect fix by today.

**Comment by swamp-agr** [comment]
Looks like it was not enough.
Now, instead of `Data.Encoding.ISO88591`there is missing `Data.Encoding.ISO88592` which is actually autogenerated. Investigating further.

**Comment by swamp-agr** [comment]
Testing simple configuration where `encoding-0.8.4` is dependency:
```
cabal-version:       >=1.24

name:                encoding-test-tmp
version:             0.1.0.0

build-type:          Simple
extra-source-files:  CHANGELOG.md

executable encoding-test-tmp
  main-is:             Main.hs
  build-depends:       base >=4.10 && <4.15
                     , encoding ==0.8.4
  default-language:    Haskell2010
```

Cabal tests:
- `==` GHC 8.2.2 (`==` Cabal 2.0.1.0) - build fail reproduced.
- `>=` GHC 8.4.1 (`>=` Cabal 2.2.0.0) - build fail not reproduced.

Stack tests (with `- encoding-0.8.4` as `extra-deps` without `package.yaml`):
- lts-12.14 (GHC 8.4.3) - build fail reproduced.
- lts-12.26 (GHC 8.4.4) - build fail reproduced.

- Seems that, stack is using Cabal `v1-` capabilities. 
- After obtaining source tarball from Hackage it tried to preprocess them. 
- I investigated the difference between `0.8` and `0.8.3`: files for pre-processing (`*.{mapping,mapping2,xml}`) were not put in source distribution.
- Seems that starting with 2.0 Cabal does not include them via `sdist` command.
- Both commands `v1-sdist` and `v2-sdist` were not capable to put files in tarball.
- After adding them via `Other-source-files` they started to be present in tarball (both commands `v1-sdist` and `v2-sdist` populate tarball).
- `stack` tool cannot work with package candidates. It could only use released packages.

Next steps:
- make build tests with package candidate with both `v1`, `v2`.
- ensure that all proper combinations of `GHC`, `Cabal` and `cabal-install` will produce builds (i.e. pre-processor is working fine).
- release package and try different tests with stack.

**Comment by swamp-agr** [comment]
`0.8.5` published occasionally and tested on following configuration:

```
cabal-version:       >=2.0
name:                encoding-test-tmp
version:             0.1.0.0
build-type:          Simple
extra-source-files:  CHANGELOG.md
executable encoding-test-tmp
  main-is:             Main.hs
  build-depends:       base >=4.10 && <5
                     , encoding ==0.8.5
  -- hs-source-dirs:
  default-language:    Haskell2010
```
Results: 
ghc | Cabal | cabal-install | stack resolver | cabal v1 install | cabal v2-build | stack build
--- | --- | --- | --- | --- | --- | --- 
8.2.2 | 2.2.0.0 | 2.2.0.1 | lts-11.22 | ✅ | ✅ | ✅  
8.4.4 | 2.2.0.0 | 2.2.0.1 | lts-12.26 | ✅ | ✅ | ✅

**Comment by swamp-agr** [comment]
@rpeszek could you please retest on `0.8.5`?

**Comment by rpeszek** [comment]
I am able to build both with stack and cabal using 0.8.5.
Thanks for this prompt fix!
